### ISSUE TITLE
masih serring error login

### ISSUE THREAD

**Issue by glhrzk** [razisek/Shopee-Live-Bot#1]
![image](https://github.com/razisek/Shopee-Live-Bot/assets/30434236/2a059e89-7eeb-4ceb-b333-62e327432255)

**Comment by razisek** [comment]
itu rerun aja bang, soalnya error pas validasi qr, rerun sampe ga muncul error

**Comment by glhrzk** [comment]
![image](https://github.com/razisek/Shopee-Live-Bot/assets/30434236/96925273-9f38-44da-abd5-f2b490f778a3)
udah coba rerun sampai qr muncul, tapi pas di scan dia gagal login, ini udah 2x

**Comment by razisek** [comment]
ada file account.json di satu folder tsb? coba liat isinya

**Comment by glhrzk** [comment]
![image](https://github.com/razisek/Shopee-Live-Bot/assets/30434236/c9a00b5c-343a-4650-970e-55be23a122a6)
ada

**Comment by glhrzk** [comment]
![image](https://github.com/razisek/Shopee-Live-Bot/assets/30434236/1582b93c-e118-45f4-9168-9707b955bf31)
sudah bisa, setelah menambah permision write ke account.json
